## Extension to GutTest.
## GogotteCompiler in turn generates extensions to this class.
## See example/_out_specimen/test_specimen.gd for a specimen of a subclass generated by GogotteCompiler.
class_name GogotteTest
extends GutTest

var ROW_INDENT: int = 10

## Context dictionary for sharing data between steps.
var ctx: Dictionary = {}

## Part of AST
var _scenarios: Variant = null

## Parallel to _scenarios: the rule each scenario belongs to (or null).
var _scenario_rules: Variant = null

## Tracks which rule ids have already had their heading printed.
var _printed_rule_ids: Dictionary = {}

## Docstring for the currently executing step.
## Can be String or null.
var docstring: Variant = null

## Datatable for the currently executing step.
## Can be Array or null.
var datatable: Variant = null

## Temporary node you can attach anything to.
var temp_node: Node = null

## gut test override
func before_all() -> void:
    # Print Feature heading before each feature.
    var ast: Variant = get("FEATURE_AST")
    if ast:
        gut.p(str("Feature: ", ast.feature.get('name', '')), 1)
        if ast.feature.has("description") and len(ast.feature.description) > 0:
            gut.p(ast.feature.description, 1)

        # Execute tag handlers
        for tag in ast.feature.get('tags', []):
            await GogotteEnvironment.exec_before_tag(self, tag.name)

        # Execute environment behaviour
        await GogotteEnvironment.exec_before_feature(self, ast.feature)

## gut test override
func after_all() -> void:
    var ast: Variant = get("FEATURE_AST")
    if ast:
        # Execute environment behaviour
        await GogotteEnvironment.exec_after_feature(self, ast.feature)

        # Execute tag handlers
        for tag in ast.feature.get('tags', []):
            await GogotteEnvironment.exec_after_tag(self, tag.name)


## gut test override
func before_each() -> void:
    # We clear the context dictionary before each test.
    ctx.clear()

## Prints to gut.p() but nicely indented.
func p(text: String, log_level: int = 0) -> void:
    var lines = text.split('\n', true)
    for line in lines:
        gut.p(str("          ", line), log_level)

# Overrides _fail() in GutTest.
func _fail(text: String) -> void:
    # We print a stack trace on failure.
    gut.p("[Stack Trace]:")

    # We print only slice(2, -3) of the stack in order to exclude stack cruft created by GUT and Gogotte.
    for frame in get_stack().slice(2, -3):
        gut.p(str("  ", frame['source'], ":",
                  frame['line'], " in ", frame['function'], "()"))

    # Return control to the normal GutTest _fail().
    super(text)

## Executes a step.
func _step(keyword: String,
           text: String,
           dataTable: Variant = null,
           docString: Variant = null) -> void:
    await GogotteEnvironment.exec_before_step(self, text)

    _print_step(keyword, text, dataTable, docString)
    await _exec_step(keyword, text, dataTable, docString)

    await GogotteEnvironment.exec_after_step(self, text)

## Gets the whitespace needed to right-align 'keyword' to position 'kw_pos'.
func _get_right_align_whitespace(kw_pos: int, keyword: String) -> String:
    var indent: String = ""
    assert(len(keyword) <= kw_pos)
    for i in range(kw_pos - len(keyword)):
        indent += " "
    return indent

func _print_step(keyword: String,
                 text: String,
                 dataTable: Variant = null,
                 docString: Variant = null) -> void:
    var indent: String = _get_right_align_whitespace(ROW_INDENT, keyword)
    gut.p(str(indent, keyword, text), 1)

    # Prints the DataTable if the step has one.
    if dataTable != null:
        # First find the widest cell in each column
        var col_widths = []
        for i in range(len(dataTable.rows[0].cells)):
            col_widths.append(-1)
        for row in dataTable.rows:
            for i in range(len(row.cells)):
                col_widths[i] = maxi(col_widths[i],
                                     len(str(row.cells[i].value)))

        # Actually print each row
        var row_indent = _get_right_align_whitespace(ROW_INDENT, "")
        for row in dataTable.rows:
            var row_str: String = row_indent
            for i in range(len(row.cells)):
                row_str += _get_right_align_whitespace(col_widths[i], row.cells[i].value)
                row_str += str(row.cells[i].value)
                row_str += ' | '
            gut.p(row_str, 1)

    # Prints the docstring if the step has one.
    if docString != null:
        var row_indent = _get_right_align_whitespace(ROW_INDENT, "")
        var content_lines = docString.split("\n")
        gut.p(str(row_indent, "\"\"\""), 1)
        for line in content_lines:
            gut.p(str(row_indent, line), 1)
        gut.p(str(row_indent, "\"\"\""), 1)

func _exec_step(keyword: String,
                text: String,
                dataTable_arg: Variant = null,
                docString_arg: Variant = null) -> void:
    # Try to match the step.
    var matched = StepLibrary.match_step(text)
    assert(matched != null, str("[Gogotte]: Undefined step: ", text))

    # Build the argument array.
    var step_def: StepDef = matched[0]
    var args = [self]
    args.append_array(matched.slice(1))

    # Load the docstring and datatable.
    if dataTable_arg != null:
        datatable = []
        for row in dataTable_arg.rows:
            var row_values = []
            for col in row.cells:
                row_values.append(col.value)
            datatable.append(row_values)
    else:
        datatable = null

    if docString_arg != null:
        docstring = docString_arg
    else:
        docstring = null

    # Call the function.
    await step_def.callable.callv(args)

## Begins the scenario.
func _begin(scenario_idx: int, outline_idx: int = -1) -> void:
    var scenario = _get_scenario(scenario_idx)

    # Print the Rule heading if this scenario belongs to a rule we haven't printed yet.
    var rule = _get_scenario_rule(scenario_idx)
    if rule != null:
        var rule_id = rule.get("id", str(scenario_idx))
        if not _printed_rule_ids.has(rule_id):
            _printed_rule_ids[rule_id] = true
            gut.p(str("Rule: ", rule.get('name', '')), 1)
            if rule.has("description") and len(rule.description) > 0:
                gut.p(rule.description, 1)

    # Execute tag handlers
    for tag in scenario.get('tags', []):
        await GogotteEnvironment.exec_before_tag(self, tag.name)

    # Create temp node
    temp_node = Node.new()
    temp_node.name = "GogotteTempNode"
    add_child(temp_node)

    # Execute pre-scenario handler
    await GogotteEnvironment.exec_before_scenario(self, scenario)

    var outline_suffix = (" - Example #" + str(outline_idx + 1)) if outline_idx != -1 else ""

    # Print out the scenario heading.
    gut.p(str("Scenario: ", scenario.name, outline_suffix), 1)
    # t.gut.p(str("Scenario: ", scenario.name), 1)
    if scenario.has("description") and len(scenario.description) > 0:
        gut.p(scenario.description, 1)

## Ends the scenario.
func _end(scenario_idx: int) -> void:
    # Execute post-scenario handler
    # (Last chance to do things to children of temp_node)
    var scenario = _get_scenario(scenario_idx)
    await GogotteEnvironment.exec_after_scenario(self, scenario)

    # Free temp_node
    # gut.p(str("Children of temp_node: ", temp_node.get_children()))
    temp_node.free()

    # Execute tag handlers
    for tag in scenario.get('tags', []):
        await GogotteEnvironment.exec_after_tag(self, tag.name)

    # Extra newline
    gut.p("", 1)

func _get_scenario(idx: int) -> Dictionary:
    if _scenarios == null:
        _build_scenario_index()
    return _scenarios[idx]

## Returns the rule dictionary that the scenario at idx belongs to, or null.
func _get_scenario_rule(idx: int) -> Variant:
    if _scenario_rules == null:
        _build_scenario_index()
    return _scenario_rules[idx]

## Populates _scenarios and _scenario_rules from the feature AST.
func _build_scenario_index() -> void:
    _scenarios = []
    _scenario_rules = []
    var ast: Variant = get("FEATURE_AST")
    for child in ast.feature.children:
        if child.has("scenario"):
            _scenarios.append(child.scenario)
            _scenario_rules.append(null)

        if child.has("rule"):
            for grandchild in child.rule.children:
                if grandchild.has("scenario"):
                    _scenarios.append(grandchild.scenario)
                    _scenario_rules.append(child.rule)
